# Ubuntu release codename
# visit: http://releases.ubuntu.com/
dist: xenial

# Disable sudo to speed up the build
sudo: false

language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

virtualenv:
  system_site_packages: false

matrix:
  include:
    # =========================== macOS ==============================
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.5 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov

    # =========================== Windows ==============================
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  allow_failures:
      - python: "nightly"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run unit tests
script:
  - coverage run -m pytest

# submit coverage
after_success:
  - codecov

